### ISSUE TITLE
Update Bower Dependancies to BB 1.1.0 and Underscore 1.5.2

### ISSUE THREAD

**Issue by chiplay** [jmorrell/backbone-paginated-collection#1]
Great extension! Just starting to test it out and its perfect for our use case. Would you be able to bump your bower dependancies up to BB 1.1.0 and Underscore 1.5.2?  Working create with the updated version of those libs and it would help clean up our bower update conflicts.  Thanks!

**Comment by jmorrell** [comment]
Hmm.. I don't want to force Backbone 1.1.0 on people who aren't ready for it. Would changing the version string to ">=1.0.0" solve your issue?

Also, this is a foundational module for a larger module called [Backbone.Obscura](https://github.com/jmorrell/backbone.obscura). It's overkill if you just need pagination, but if you need to do filtering or sorting as well, it's a big help.

**Comment by chiplay** [comment]
That would do the trick – thanks!
I will definitely check out backbone obscura, it looks like a great fit for our Marionette app.

**Comment by jmorrell** [comment]
Okay, cool. I'll get those version strings updated today :+1:

**Comment by jmorrell** [comment]
Updated in this commit: https://github.com/jmorrell/backbone-paginated-collection/commit/074a6a3c3e6f1c0cb72670e82e6876ddd8069aab Please let me know if that doesn't resolve the issue :)

**Comment by chiplay** [comment]
Perfecto. Thanks again.
